{{- if .Values.conf.values }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shib-idp.fullname" . }}-conf
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.conf.values }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}

{{- if .Values.credentials.values }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shib-idp.fullname" . }}-creds
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.credentials.values }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}

{{- if .Values.oidc.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shib-idp.fullname" . }}-oidc
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
data:
  oidc.conf: |-
    <VirtualHost *:8081>
      OIDCProviderMetadataURL https://login.microsoftonline.com/{{ .Values.oidc.tenantID }}/.well-known/openid-configuration
      OIDCClientID {{ .Values.oidc.clientID }}
      OIDCClientSecret ${OIDC_CLIENT_SECRET}
      OIDCRedirectURI https://{{ index .Values.ingress.hosts 0 }}/.oidc/redirect
      OIDCCryptoPassphrase {{ .Values.oidc.passphrase }}
      OIDCScope "openid profile"

      OIDCSessionInactivityTimeout 120
      OIDCSessionMaxDuration 120
      OIDCAuthRequestParams "prompt=login&max_age=0"

      OIDCRemoteUserClaim upn ^(.*)@

      ProxyAddHeaders On

      ProxyPass / http://localhost:8080/ flushpackets=on disablereuse=On connectiontimeout=300
      ProxyPassReverse / http://localhost:8080/

      <Location /idp/authn/RemoteUser>
        AuthType openid-connect
        Require valid-user
      </Location>

      <Location /.oidc/redirect>
        AuthType openid-connect
        Require valid-user
      </Location>
    </VirtualHost>
{{- end }}