{{- if .Values.conf.values }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shib-idp.fullname" . }}-conf
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.conf.values }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}

{{- if .Values.credentials.values }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shib-idp.fullname" . }}-creds
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.credentials.values }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
