{{- if .Values.ingress.enabled }}
{{- $fullName := include "shib-idp.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end  }}
spec:
  rules:    
    - host: {{ .Values.ingress.hosts | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.paths | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 443
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4}}
  {{- end }}
{{- end }}
