{{- if .Values.oidc.enabled }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "shib-idp.fullname" . }}-oidc
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
spec:
  encryptedData:
    OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSealedSecret | quote }}
{{- end }}

{{- if .Values.conf.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "shib-idp.fullname" . }}-conf
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
spec:
  encryptedData:
  {{- range $k, $v := .Values.conf.sealedSecrets }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

{{- if .Values.credentials.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "shib-idp.fullname" . }}-creds
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
spec:
  encryptedData:
  {{- range $k, $v := .Values.credentials.sealedSecrets }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}

{{- if .Values.properties.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "shib-idp.fullname" . }}-props
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
spec:
  encryptedData:
  {{- range $k, $v := .Values.properties.sealedSecrets }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}