apiVersion: v1
kind: Service
metadata:
  name: {{ include "shib-idp.fullname" . }}
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    {{- include "shib-idp.selectorLabels" . | nindent 4 }}
