apiVersion: v1
kind: Service
metadata:
  name: {{ include "shib-idp.fullname" . }}
  labels:
    {{- include "shib-idp.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: http-tomcat
      protocol: TCP
      name: http
    - port: 8443
      targetPort: https-tomcat
      protocol: TCP
      name: https
    {{ if .Values.oidc.enabled }}
    - port: 8081
      targetPort: http-apache
      protocol: TCP
      name: http-apache
    {{- end }}
  selector:
    {{- include "shib-idp.selectorLabels" . | nindent 4 }}
