apiVersion: v1
kind: Service
metadata:
  name: {{ include "shibboleth-idp.fullname" . }}
  labels:
    {{- include "shibboleth-idp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.containerPort }}}}
      protocol: TCP
      name: http
  selector:
    {{- include "shibboleth-idp.selectorLabels" . | nindent 4 }}
