name: Release Dev Charts

on:
  push:
    branches:
      - 'dev/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        # https://github.com/marketplace/actions/helm-chart-releaser

      - name: Install Helm
        uses: azure/setup-helm@v3
        
      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.5.0
        with: 
          config: dev-chart-config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
