name: Update gh-pages files

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - 'dev/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-branch:
    name: Update gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Merge branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          message: Update gh-pages branch
          target_branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false