name: Update gh-pages files

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - 'dev/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-branch:
    name: Update gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false